#!/usr/bin/python
import webcolors

color_value = 0

def closest_colour(requested_colour):
    min_colours = {}
    for key, name in webcolors.css3_hex_to_names.items():
        r_c, g_c, b_c = webcolors.hex_to_rgb(key)
        rd = (r_c - requested_colour[0]) ** 2
        gd = (g_c - requested_colour[1]) ** 2
        bd = (b_c - requested_colour[2]) ** 2
        min_colours[(rd + gd + bd)] = name
    return min_colours[min(min_colours.keys())]

def get_colour_name(requested_colour):
    try:
        closest_name = actual_name = webcolors.rgb_to_name(requested_colour)
    except ValueError:
        closest_name = closest_colour(requested_colour)
        actual_name = None
    return actual_name, closest_name
    
def color_codes(color_name):
    if(color_name=='aliceblue'):
        color_value=100
    elif(color_name=='antiquewhite'):
        color_value=200
    elif(color_name=='aqua'):
        color_value=101
    elif(color_name=='aquamarine'):
        color_value=102
    elif(color_name=='azuare'):
        color_value=201
    elif(color_name=='beige'):
        color_value=202
    elif(color_name=='bisque'):
        color_value=300
    elif(color_name=='black'):
        color_value=400
    elif(color_name=='blanchedalmond'):
        color_value=301
    elif(color_name=='blue'):
        color_value=102
    elif(color_name=='blueviolet'):
        color_value=103
    elif(color_name=='brown'):
        color_value=500
    elif(color_name=='burlywood'):
        color_value=501
    elif(color_name=='cadetblue'):
        color_value=104
    elif(color_name=='chartreuse'):
        color_value=600
    elif(color_name=='chocolate'):
        color_value=502
    elif(color_name=='coral'):
        color_value=503
    elif(color_name=='cornflowerblue'):
        color_value=105
    elif(color_name=='cornsilk'):
        color_value=203
    elif(color_name=='crimson'):
        color_value=301
    elif(color_name=='cyan'):
        color_value=700
    elif(color_name=='darkblue'):
        color_value=106
    elif(color_name=='darkcyan'):
        color_value=701
    elif(color_name=='darkgoldenrod'):
        color_value=504
    elif(color_name=='darkgray'):
        color_value=800
    elif(color_name=='darkgrey'):
        color_value=800
    elif(color_name=='darkgreen'):
        color_value=601
    elif(color_name=='darkkhaki'):
        color_value=505
    elif(color_name=='darkmagenta'):
        color_value=900
    elif(color_name=='darkolivegreen'):
        color_value=602
    elif(color_name=='darkorange'):
        color_value=1000
    elif(color_name=='darkorchid'):
        color_value=901
    elif(color_name=='darkred'):
        color_value=1100
    elif(color_name=='darksalmon'):
        color_value=506
    elif(color_name=='darkseagreen'):
        color_value=603
    elif(color_name=='darkslateblue'):
        color_value=107
    elif(color_name=='darkslategray'):
        color_value=801
    elif(color_name=='darkslategrey'):
        color_value=801
    elif(color_name=='darkturquoise'):
        color_value=108
    elif(color_name=='darkviolet'):
        color_value=902
    elif(color_name=='deeppink'):
        color_value=302
    elif(color_name=='deepskyblue'):
        color_value=109
    elif(color_name=='dimgray'):
        color_value=802
    elif(color_name=='dimgrey'):
        color_value=802
    elif(color_name=='dodgerblue'):
        color_value=110
    elif(color_name=='firebrick'):
        color_value=507
    elif(color_name=='floralwhite'):
        color_value=204
    elif(color_name=='forestgreen'):
        color_value=604
    elif(color_name=='fuchsia'):
        color_value=303
    elif(color_name=='gainsboro'):
        color_value=205
    elif(color_name=='ghostwhite'):
        color_value=206
    elif(color_name=='gold'):
        color_value=1200
    elif(color_name=='goldenrod'):
        color_value=506
    elif(color_name=='gray'):
        color_value=803
    elif(color_name=='grey'):
        color_value=803
    elif(color_name=='green'):
        color_value=605
    elif(color_name=='greenyellow'):
        color_value=606
    elif(color_name=='honeydew'):
        color_value=207
    elif(color_name=='hotpink'):
        color_value=304
    elif(color_name=='indianred'):
        color_value=509
    elif(color_name=='indigo'):
        color_value=111
    elif(color_name=='ivory'):
        color_value=208
    elif(color_name=='khaki'):
        color_value=1201
    elif(color_name=='lavender'):
        color_value=112
    elif(color_name=='lavenderblush'):
        color_value=305
    elif(color_name=='lawngreen'):
        color_value=607
    elif(color_name=='lemonchiffon'):
        color_value=209
    elif(color_name=='lightblue'):
        color_value=113
    elif(color_name=='lightcoral'):
        color_value=510
    elif(color_name=='lightcyan'):
        color_value=210
    elif(color_name=='lightgoldenrodyellow'):
        color_value=1202
    elif(color_name=='lightgray'):
        color_value=804
    elif(color_name=='lightgrey'):
        color_value=804
    elif(color_name=='lightgreen'):
        color_value=608
    elif(color_name=='lightpink'):
        color_value=306
    elif(color_name=='lightsalmon'):
        color_value=511
    elif(color_name=='lightseagreen'):
        color_value=609
    elif(color_name=='lightskyblue'):
        color_value=114
    elif(color_name=='lightslategray'):
        color_value=805
    elif(color_name=='lightslategrey'):
        color_value=805
    elif(color_name=='lightsteelblue'):
        color_value=115
    elif(color_name=='lightyellow'):
        color_value=1203
    elif(color_name=='lime'):
        color_value=610
    elif(color_name=='limegreen'):
        color_value=611
    elif(color_name=='linen'):
        color_value=211
    elif(color_name=='magenta'):
        color_value=307
    elif(color_name=='maroon'):
        color_value=512
    elif(color_name=='mediumaquamarine'):
        color_value=612
    elif(color_name=='mediumblue'):
        color_value=116
    elif(color_name=='mediumorchid'):
        color_value=903
    elif(color_name=='mediumpurple'):
        color_value=904
    elif(color_name=='mediumseagreen'):
        color_value=613
    elif(color_name=='mediumslateblue'):
        color_value=117
    elif(color_name=='mediumspringgreen'):
        color_value=614
    elif(color_name=='mediumturquoise'):
        color_value=118
    elif(color_name=='mediumvioletred'):
        color_value=307
    elif(color_name=='midnightblue'):
        color_value=119
    elif(color_name=='mintcream'):
        color_value=212
    elif(color_name=='mistyrose'):
        color_value=308
    elif(color_name=='moccasin'):
        color_value=309
    elif(color_name=='navajowhite'):
        color_value=310
    elif(color_name=='navy'):
        color_value=120
    elif(color_name=='oldlace'):
        color_value=213
    elif(color_name=='olive'):
        color_value=615
    elif(color_name=='olivedrab'):
        color_value=616
    elif(color_name=='orange'):
        color_value=1001
    elif(color_name=='orangered'):
        color_value=1101
    elif(color_name=='orchid'):
        color_value=905
    elif(color_name=='palegoldenrod'):
        color_value=513
    elif(color_name=='palegreen'):
        color_value=617
    elif(color_name=='paleturquoise'):
        color_value=121
    elif(color_name=='palevioletred'):
        color_value=514
    elif(color_name=='papayawhip'):
        color_value=311
    elif(color_name=='peachpuff'):
        color_value=312
    elif(color_name=='peru'):
        color_value=515
    elif(color_name=='pink'):
        color_value=313
    elif(color_name=='plum'):
        color_value=906
    elif(color_name=='powderblue'):
        color_value=122
    elif(color_name=='purple'):
        color_value=907
    elif(color_name=='red'):
        color_value=1102
    elif(color_name=='rosybrown'):
        color_value=516
    elif(color_name=='royalblue'):
        color_value=123
    elif(color_name=='saddlebrown'):
        color_value=517
    elif(color_name=='salmon'):
        color_value=518
    elif(color_name=='sandybrown'):
        color_value=519
    elif(color_name=='seagreen'):
        color_value=618
    elif(color_name=='seashell'):
        color_value=314
    elif(color_name=='sienna'):
        color_value=520
    elif(color_name=='silver'):
        color_value=806
    elif(color_name=='skyblue'):
        color_value=124
    elif(color_name=='slateblue'):
        color_value=125
    elif(color_name=='slategray'):
        color_value=807
    elif(color_name=='slategrey'):
        color_value=807
    elif(color_name=='snow'):
        color_value=214
    elif(color_name=='springgreen'):
        color_value=619
    elif(color_name=='steelblue'):
        color_value=126
    elif(color_name=='tan'):
        color_value=521
    elif(color_name=='teal'):
        color_value=127
    elif(color_name=='thistle'):
        color_value=908
    elif(color_name=='tomato'):
        color_value=1103
    elif(color_name=='turquoise'):
        color_value=128
    elif(color_name=='violet'):
        color_value=315
    elif(color_name=='wheat'):
        color_value=522
    elif(color_name=='white'):
        color_value=215
    elif(color_name=='whitesmoke'):
        color_value=216
    elif(color_name=='yellow'):
        color_value=1204
    elif(color_name=='yellowgreen'):
        color_value=602
    else:
        color_value=0
    return color_value

def get_color_code(requested_color):
    close_color_name = closest_colour(requested_color)
    return color_codes(close_color_name)
    